MAIN_URL = "https://www.eyrein-industrie.com/"
SHOP_URL = "https://boutique.eyrein-industrie.com/"
BLOCK = ".column.small-12.medium-6.large-4 a"
REF = ".product--reference span"
TITLE = ".product--title"
SHEETS = ".accordion-content-bis p a"
JSON_FILE = "Products.json"
LOG_FILE = "products.log"